### ISSUE TITLE
Suggestion for a new line and comment between lines 19 & 20.

### ISSUE THREAD

**Issue by OddEssA** [Ejay-3D/Marlin-Biqu#1]
Suggestion for a new line and comment between lines 19 & 20.

M117 Park nozzle to start purge line	      ; Set LCD Message: "Park nozzle to start purge line" (Définir le message LCD : Parcage de la buse au début de la ligne de purge)

**Comment by OddEssA** [comment]
M117 Park extruder to start purge line	      ; Set LCD Message: "Park nozzle to start purge line" (Définir le message LCD : Parcage de la buse au début de la ligne de purge)

**Comment by Ejay-3D** [comment]
Thank you for your proposition , I'll add you as contributor so you can propose change via pull request .

**Comment by OddEssA** [comment]
You're Welcome.
Thank you for your propose.

**Comment by Ejay-3D** [comment]
Gcode updated , closing issue
